version: '3'
services:
  nis:
    build:
      context: ./
      dockerfile: Dockerfile_nis
    container_name: nis
    ports:
      - 7890:7890
    network_mode: host
    command: ./nix.runNis.sh
  poll:
    build:
      context: ./
      dockerfile: Dockerfile_node
    container_name: poll
    ports:
      - 8081:8081
    network_mode: host
    command: 
      - /bin/sh
      - -c
      - |
        cd /usr/local/poll_data_nodejs
        npm install babel-cli -g
        npm i
        npm start
  db:
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: explorer_es
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 9306:3306
    network_mode: host