version: '3'
services:
  explorer_es:
    image: maskerlee/explorer_es
    container_name: explorer_es
    ports:
      - 8080:8080
    network_mode: host
    volumes: 
      - ../nis:/usr/local/NIS-Explorer-V2/nis-data
    command: 
      - /bin/sh
      - -c
      - |
        chmod 777 run_explorer.sh
        ./run_explorer.sh