version: '3'
services:
  explorer_es:
    image: maskerlee/explorer_es
    container_name: explorer_es
    ports:
      - 8080:8080
    network_mode: host
    volumes: 
      - ../nis:/usr/local/NIS-Explorer-V2/nis-data
    depends_on:
      - poll
      - mysql
    command: 
      - /bin/sh
      - -c
      - |
        chmod 777 run_explorer.sh
        ./run_explorer.sh
  poll:
    image: maskerlee/poll
    container_name: poll
    ports:
      - 8081:8081
    network_mode: host
    command: 
      - /bin/sh
      - -c
      - |
        cd /usr/local/poll_data_nodejs
        npm install babel-cli -g
        npm i
        npm start
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: explorer_es
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 9306:3306