version: '3'
services:
  nis:
    build:
      context: ./
    image: maskerlee/nis
    container_name: nis
    ports:
      - 7890:7890
    network_mode: host
    volumes: 
      - ./:/root/nem/nis/data
    command: 
      - /bin/sh
      - -c
      - |
        chmod 777 nix.runNis.sh
        ./nix.runNis.sh